mode: learning
media_root: media
media_url: /media
base_url: /

template: hyde.ext.templates.jinja.Jinja2Template

plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
    - hyde.ext.plugins.tagger.TaggerPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin

context:
    data:
        author:
            name: Michael Wilson
            url: "http://wilsoniya.com"
        menu:
            - title: Home
              url: index.html
            - title: About
              url: about.html
            - title: Blog
              url: blog
meta:
    nodemeta: meta.yaml
    created: !!timestamp 2010-01-01 00:00:00
    author: Michael Wilson

sorter:
    created:
        attr: source_file.kind
#            - meta.created
        reverse: true
        filters:
            meta.listable: true
            source_file.kind: html

