mode: learning
media_root: media
media_url: /media
base_url: /
mode: development
#mode: production

template: hyde.ext.templates.jinja.Jinja2Template

plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
    - hyde.ext.plugins.tagger.TaggerPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
    - hyde.ext.plugins.paginator.PaginatorPlugin

context:
    data:
        author:
            name: Michael Wilson
            url: "http://wilsoniya.com"
        menu:
            - title: Home
              url: index.html
            - title: About
              url: about.html
            - title: Blog
              url: blog
meta:
    nodemeta: meta.yaml
    created: !!timestamp 2010-01-01 00:00:00
    author: Michael Wilson

sorter:
    created:
        attr: meta.created
        reverse: true
        filters:
            meta.listable: true
            source_file.kind: html

publisher:
    github:
        type: hyde.ext.publishers.dvcs.Git
        path: ../
        branch: gh-pages
        url: git@github.com:wilsoniya/wilsoniya.com.git

